name: 'openwrt builder'

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ['x86-64']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget
      - uses: actions/cache@v3
        with:
          key: openwrt-${{ matrix.TARGET }}
          path: openwrt
      - name: extract source
        run: |
          [[ ! -e openwrt ]] && git clone https://github.com/immortalwrt/immortalwrt openwrt
          cp config/${{ matrix.TARGET }}.config openwrt/.config
          cd openwrt
          git pull --rebase
          git checkout openwrt-18.06-k5.4
      - name: compile
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download
          make
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ matrix.TARGET }}
          path: openwrt

