name: 'openwrt builder'

on: [push]

env:
  REPO: https://github.com/immortalwrt/immortalwrt
  TAG: openwrt-21.02

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ['x86-64', 'bcm27xx-bcm2711']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget
      - uses: actions/cache@v3
        with:
          key: openwrt-${{ matrix.TARGET }}
          path: openwrt
      - name: extract source
        run: |
          [[ ! -e openwrt ]] && git clone ${REPO} openwrt
          cp config/${{ matrix.TARGET }}.config openwrt/.config
          cd openwrt
          git pull --rebase
          git checkout ${TAG}
      - name: compile
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
            cd openwrt
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make defconfig
            make download
            make
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ matrix.TARGET }}
          path: openwrt/bin

