name: 'openwrt builder'

on: [push]

env:
  REPO: https://github.com/coolsnowwolf/lede.git
  TAG: 20230609

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ['bcm27xx-bcm2711']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget
      - name: extract source
        run: |
          git clone -b ${TAG} --single-branch --filter=blob:none ${REPO} openwrt
      - name: compile
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 180
          max_attempts: 3
          command: |
            cd openwrt
            sed -i '/helloworld/{s/^#//}' feeds.conf.default
            ./scripts/feeds update -a
            ./scripts/feeds install -a
            make defconfig
            make -j$(nproc) download clean world
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ matrix.TARGET }}
          path: openwrt/bin

