name: 'openwrt builder'

on:
  push:
    branchs:
      - master

env:
  PACKAGES: 'shadowsocks-libev-ss-local shadowsocks-libev-ss-redir shadowsocks-libev-ss-rules shadowsocks-libev-ss-tunnel luci-app-shadowsocks-libev
    luci-app-samba4
    openconnect openssl-util openvpn-openssl luci-app-openvpn
    etherwake luci-app-wol'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: '--privileged'
    strategy:
      matrix:
        TARGET: ['bcm27xx-bcm2711', 'x86-64']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          pacman -Syy
          pacman -S --noconfirm --needed base-devel autoconf automake bash binutils bison \
            bzip2 fakeroot file findutils flex gawk gcc gettext git grep groff \
            gzip libelf libtool libxslt m4 make ncurses openssl patch pkgconf \
            python rsync sed texinfo time unzip util-linux wget which zlib
          pacman -S --noconfirm --needed asciidoc help2man intltool perl-extutils-makemaker swig
      - uses: actions/cache@v3
        with:
          key: openwrt-imagebuilder-${{ matrix.TARGET }}
          path: openwrt-imagebuilder-*
      - name: build image
        env:
          TARGET: ${{ matrix.TARGET }}
        run: |
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-image-${{ matrix.TARGET }}
          path: |
            openwrt-imagebuilder*/**/*.img.gz

