name: 'openwrt builder'

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: '--privileged'
    strategy:
      matrix:
        TARGET: ['bcm27xx-bcm2711', 'x86-64']
        VERSION: ['21.02.1']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          pacman -Syy
          pacman -S --noconfirm --needed base-devel autoconf automake bash binutils bison \
            bzip2 fakeroot file findutils flex gawk gcc gettext git grep groff \
            gzip libelf libtool libxslt m4 make ncurses openssl patch pkgconf \
            python rsync sed texinfo time unzip util-linux wget which zlib
          pacman -S --noconfirm --needed asciidoc help2man intltool perl-extutils-makemaker swig
      - uses: actions/cache@v3
        with:
          key: openwrt-${{ matrix.TARGET }}
          path: openwrt-${{ matrix.TARGET }}*
      - name: build image
        env:
          TARGET: ${{ matrix.TARGET }}
          VERSION: ${{ matrix.VERSION }}
        run: |
          ./build.sh

