name: 'openwrt builder'

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: '--privileged'
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          pacman -Syy
          pacman -S --noconfirm --needed base-devel autoconf automake bash binutils bison \
            bzip2 fakeroot file findutils flex gawk gcc gettext git grep groff \
            gzip libelf libtool libxslt m4 make ncurses openssl patch pkgconf \
            python rsync sed texinfo time unzip util-linux wget which zlib
          pacman -S --noconfirm --needed asciidoc help2man intltool perl-extutils-makemaker swig
      - uses: actions/cache@v3
        with:
          key: openwrt
          path: openwrt
      - name: extract source
        run: |
          [[ ! -e openwrt ]] && git clone https://github.com/immortalwrt/immortalwrt openwrt
          cp config/x86-64.config openwrt/.config
          cd openwrt
          git pull --rebase
          git checkout openwrt-18.06-k5.4
      - name: compile
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download
          make
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt
          path: openwrt

