name: 'openwrt builder'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ['bcm27xx-bcm2711', 'x86-64']
        REPO:
          - url: https://github.com/coolsnowwolf/lede.git
            tag: 20230609
          - url: https://github.com/openwrt/openwrt.git
            tag: v23.05.0-rc4
    steps:
      - run: |
          curl -L https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget qemu-system
      - name: prepare
        run: |
          git clone -b ${{ matrix.REPO.tag }} --single-branch --filter=blob:none ${{ matrix.REPO.url }} openwrt
          cd openwrt
          echo 'src-git helloworld https://github.com/fw876/helloworld.git' >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ${{ github.workspace }}/config/${{ matrix.TARGET }}.diffconfig ./.config
          make defconfig
      - name: compile
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 180
          max_attempts: 3
          command: |
            cd openwrt
            make -j$(nproc) download clean world
          new_command_on_retry: |
            cd openwrt
            make -j1 V=sc download clean world
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ matrix.TARGET }}
          path: openwrt/bin

