name: 'openwrt builder'

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: '--privileged'
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          pacman -Syy
          pacman -S --noconfirm --needed base-devel autoconf automake bash binutils bison \
            bzip2 fakeroot file findutils flex gawk gcc gettext git grep groff \
            gzip libelf libtool libxslt m4 make ncurses openssl patch pkgconf \
            python rsync sed texinfo time unzip util-linux wget which zlib
          pacman -S --noconfirm --needed asciidoc help2man intltool perl-extutils-makemaker swig
      - name: build image
        run: |
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: lede
          path: lede

