name: 'openwrt builder'

on: [push]

env:
  REPO: https://github.com/coolsnowwolf/lede.git
  TAG: 20230609

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TARGET: ['bcm27xx-bcm2711', 'x86-generic']
    steps:
      - uses: actions/checkout@v3
      - name: installing deps
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget
      - uses: actions/cache@v3
        with:
          key: lede-${{ matrix.TARGET }}-${{ env.TAG }}
          path: openwrt
      - name: prepare
        run: |
          [ -d openwrt ] && (cd openwrt && git pull --rebase || true)
          [ ! -e openwrt ] && git clone -b ${TAG} --single-branch --filter=blob:none ${REPO} openwrt
          cd openwrt
          sed -i '/helloworld/{s/^#src/src/}' feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ${{ github.workspace }}/config/${{ matrix.TARGET }}.diffconfig ./.config
          make defconfig
          cat feeds.conf.default
          cat .config
      - name: compile
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 180
          max_attempts: 3
          command: |
            cd openwrt
            make -j$(nproc) clean world
      - uses: actions/upload-artifact@v3
        with:
          name: openwrt-${{ matrix.TARGET }}
          path: openwrt/bin

